window.SEED_ARTISTS = [
  { name: "1991", primary_genre: "DnB", secondary_genre: "Dancefloor DnB" },
  { name: "999999999", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "A.M.C", primary_genre: "DnB", secondary_genre: "Jump Up DnB" },
  { name: "ABOVE & BEYOND", primary_genre: "Trance", secondary_genre: "Melodic/Progressive House" },
  { name: "ADIEL", primary_genre: "Techno", secondary_genre: null },
  { name: "ADRIATIQUE", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "ADVENTURE CLUB", primary_genre: "Dubstep", secondary_genre: "Melodic Bass" },
  { name: "AHEE", primary_genre: "Dubstep", secondary_genre: "Bass Music" },
  { name: "AHMED SPINS", primary_genre: "Afro House", secondary_genre: "Melodic/Progressive House" },
  { name: "ALISON WONDERLAND", primary_genre: "Bass Music", secondary_genre: "Trap" },
  { name: "ANDREW RAYEL", primary_genre: "Trance", secondary_genre: null },
  { name: "ANNA", primary_genre: "Techno", secondary_genre: null },
  { name: "ARMIN VAN BUUREN", primary_genre: "Trance", secondary_genre: null },
  { name: "ASTRIX", primary_genre: "Psytrance", secondary_genre: null },
  { name: "ATLIENS", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "AUDIOFREQ", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "AVALON EMERSON", primary_genre: "Techno", secondary_genre: "House" },
  { name: "BELTRAN", primary_genre: "Tech House", secondary_genre: null },
  { name: "BILLY GILLIES", primary_genre: "Trance", secondary_genre: "Hard Dance" },
  { name: "BLACK TIGER SEX MACHINE", primary_genre: "Dubstep", secondary_genre: "Bass Music" },
  { name: "BOOGIE T", primary_genre: "Dubstep", secondary_genre: null },
  { name: "BOU", primary_genre: "DnB", secondary_genre: "Jump Up DnB" },
  { name: "BOYS NOIZE", primary_genre: "House", secondary_genre: "Techno" },
  { name: "CASSIAN", primary_genre: "Melodic/Progressive House", secondary_genre: null },
  { name: "THE CHAINSMOKERS", primary_genre: "Pop EDM", secondary_genre: "Progressive House" },
  { name: "CHARLOTTE DE WITTE", primary_genre: "Techno", secondary_genre: null },
  { name: "CHRIS LORENZO", primary_genre: "Bass House", secondary_genre: "Tech House" },
  { name: "CHRIS STUSSY", primary_genre: "Tech House", secondary_genre: "Minimal/Deep Tech" },
  { name: "CID", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "CLOONEE", primary_genre: "Tech House", secondary_genre: null },
  { name: "COLD BLUE", primary_genre: "Trance", secondary_genre: null },
  { name: "COSMIC GATE", primary_genre: "Trance", secondary_genre: null },
  { name: "CRISTOPH", primary_genre: "Melodic/Progressive House", secondary_genre: null },
  { name: "CULTURE SHOCK", primary_genre: "DnB", secondary_genre: null },
  { name: "DA TWEEKAZ", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "DABIN", primary_genre: "Melodic Bass", secondary_genre: null },
  { name: "DARUDE", primary_genre: "Trance", secondary_genre: null },
  { name: "DEATHPACT", primary_genre: "Bass Music", secondary_genre: "Midtempo" },
  { name: "DELTA HEAVY", primary_genre: "DnB", secondary_genre: null },
  { name: "DJ ISAAC", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "DJ TENNIS", primary_genre: "House", secondary_genre: "Melodic/Progressive House" },
  { name: "DOCTOR P", primary_genre: "Dubstep", secondary_genre: null },
  { name: "FLUX PAVILION", primary_genre: "Dubstep", secondary_genre: null },
  { name: "ELI BROWN", primary_genre: "Techno", secondary_genre: "Tech House" },
  { name: "EPTIC", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "SPACE LACES", primary_genre: "Dubstep", secondary_genre: "Bass Music" },
  { name: "FISHER", primary_genre: "Tech House", secondary_genre: null },
  { name: "FUNK TRIBU", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "GARETH EMERY", primary_genre: "Trance", secondary_genre: null },
  { name: "GETTER", primary_genre: "Dubstep", secondary_genre: null },
  { name: "GHENGAR", primary_genre: "Dubstep", secondary_genre: "Bass Music" },
  { name: "HAMDI", primary_genre: "Dubstep", secondary_genre: null },
  { name: "HANNAH LAING", primary_genre: "Techno", secondary_genre: "Hard Dance" },
  { name: "HARDWELL", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "HYBRID MINDS", primary_genre: "DnB", secondary_genre: "Liquid DnB" },
  { name: "I HATE MODELS", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "ILAN BLUESTONE", primary_genre: "Trance", secondary_genre: "Melodic/Progressive House" },
  { name: "INDIRA PAGANOTTO", primary_genre: "Techno", secondary_genre: "Psytrance" },
  { name: "INFEKT", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "SAMPLIFIRE", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "INNELLEA", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "INTERPLANETARY CRIMINAL", primary_genre: "UK Garage/Bassline", secondary_genre: null },
  { name: "JOHN SUMMIT", primary_genre: "Tech House", secondary_genre: null },
  { name: "JOSEPH CAPRIATI", primary_genre: "Techno", secondary_genre: null },
  { name: "KAI WACHI", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "KASKADE", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "KETTAMA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "KEVIN DE VRIES", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "KLANGKUENSTLER", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "KOROLOVA", primary_genre: "Melodic/Progressive House", secondary_genre: null },
  { name: "KREAM", primary_genre: "House", secondary_genre: null },
  { name: "LADY FAITH", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "LAIDBACK LUKE", primary_genre: "House", secondary_genre: null },
  { name: "LAYTON GIORDANI", primary_genre: "Techno", secondary_genre: null },
  { name: "LEVEL UP", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "LEVITY", primary_genre: "Bass Music", secondary_genre: "Dubstep" },
  { name: "LIL TEXAS", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "LILLY PALMER", primary_genre: "Techno", secondary_genre: null },
  { name: "LUCIANO", primary_genre: "Tech House", secondary_genre: "Minimal/Deep Tech" },
  { name: "LUUK VAN DIJK", primary_genre: "Tech House", secondary_genre: "Minimal/Deep Tech" },
  { name: "MADDIX", primary_genre: "Techno", secondary_genre: null },
  { name: "MARTIN GARRIX", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "MASSANO", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "MATHAME", primary_genre: "Melodic/Progressive House", secondary_genre: null },
  { name: "MEDUZA", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "MISH", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "MUZZ", primary_genre: "DnB", secondary_genre: null },
  { name: "NICO MORENO", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "NOIZU", primary_genre: "Bass House", secondary_genre: "Tech House" },
  { name: "NOSTALGIX", primary_genre: "Bass House", secondary_genre: null },
  { name: "NOTION", primary_genre: "UK Garage/Bassline", secondary_genre: null },
  { name: "OMNOM", primary_genre: "Bass House", secondary_genre: null },
  { name: "PAUL OAKENFOLD", primary_genre: "Trance", secondary_genre: null },
  { name: "PAUL VAN DYK", primary_genre: "Trance", secondary_genre: null },
  { name: "PEEKABOO", primary_genre: "Dubstep", secondary_genre: "Bass Music" },
  { name: "PEGGY GOU", primary_genre: "House", secondary_genre: null },
  { name: "PORTER ROBINSON", primary_genre: "Melodic/Progressive House", secondary_genre: "Electro Pop" },
  { name: "THE PRODIGY", primary_genre: "Bass Music", secondary_genre: "Rave" },
  { name: "THE PURGE", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "RAY VOLPE", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "REBEKAH", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "REBUKE", primary_genre: "Techno", secondary_genre: "Melodic/Progressive House" },
  { name: "RIOT", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "ROOLER", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "SAMMY VIRJI", primary_genre: "UK Garage/Bassline", secondary_genre: "Bass House" },
  { name: "SAN HOLO", primary_genre: "Melodic Bass", secondary_genre: "Future Bass" },
  { name: "SAN PACHO", primary_genre: "Bass House", secondary_genre: "Tech House" },
  { name: "SEVEN LIONS", primary_genre: "Melodic Bass", secondary_genre: "Trance" },
  { name: "SHINGO NAKAMURA", primary_genre: "Melodic/Progressive House", secondary_genre: null },
  { name: "SHIP WREK", primary_genre: "Bass House", secondary_genre: "Tech House" },
  { name: "SKREAM", primary_genre: "Dubstep", secondary_genre: "UK Garage/Bassline" },
  { name: "SOFI TUKKER", primary_genre: "House", secondary_genre: "Pop EDM" },
  { name: "SOLOMUN", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "STAN CHRIST", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "STEVE AOKI", primary_genre: "House", secondary_genre: "Pop EDM" },
  { name: "SUB FOCUS", primary_genre: "DnB", secondary_genre: null },
  { name: "SUB ZERO PROJECT", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "SUBTRONICS", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "T78", primary_genre: "Techno", secondary_genre: null },
  { name: "THOMAS SCHUMACHER", primary_genre: "Techno", secondary_genre: null },
  { name: "TIESTO", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "TINLICKER", primary_genre: "Melodic/Progressive House", secondary_genre: null },
  { name: "UNDERWORLD", primary_genre: "Techno", secondary_genre: null },
  { name: "VINTAGE CULTURE", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "VIRTUAL RIOT", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "WARFACE", primary_genre: "Hardstyle", secondary_genre: null },
  { name: "WAX MOTIF", primary_genre: "Bass House", secondary_genre: "House" },
  { name: "WESTEND", primary_genre: "Tech House", secondary_genre: null },
  { name: "WILLIAM BLACK", primary_genre: "Melodic Bass", secondary_genre: "Future Bass" },
  { name: "WOOLI", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "ZEDD", primary_genre: "Pop EDM", secondary_genre: "House" }
];
