window.SEED_ARTISTS = [
  { name: "1991", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "999999999", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "A.M.C with MC PHANTOM", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "ABANA B2B JULIET MENDOZA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "ABOVE & BEYOND", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "ADIEL", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "ADRIÁN MILLS", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "ADRIATIQUE", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "ADVENTURE CLUB", primary_genre: "Melodic Dubstep", secondary_genre: "Dubstep" },
  { name: "ÆON:MODE", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "AHEE B2B LIQUID STRANGER", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "AHMED SPINS", primary_genre: "Afro House", secondary_genre: "House" },
  { name: "ALISON WONDERLAND", primary_genre: "Trap", secondary_genre: "Pop EDM" },
  { name: "ALVES", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "ALYSSA JOLEE", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "ANASTAZJA", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "ANDREW RAYEL", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "ANNA", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "AR/CO", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "ARGY", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "ARMIN VAN BUUREN", primary_genre: "Melodic/Progressive House", secondary_genre: "Pop EDM" },
  { name: "ASTRIX", primary_genre: "Psytrance", secondary_genre: "Psytrance" },
  { name: "ATLIENS", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "AUDIOFREQ", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "AVALON EMERSON", primary_genre: "Techno", secondary_genre: "House" },
  { name: "BELTRAN", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "BILLY GILLIES", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "BLACK TIGER SEX MACHINE", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "BOOGIE T", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "BOU", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "BOYS NOIZE", primary_genre: "Techno", secondary_genre: "House" },
  { name: "BUNT.", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "CASSIAN", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "THE CHAINSMOKERS", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "CHARLOTTE DE WITTE", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "CHRIS LORENZO", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "CHRIS STUSSY", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "CID", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "CLAWZ", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "CLOONEE", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "CLOUDY", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "CLUB ANGEL", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "COLD BLUE", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "CONFIDENCE MAN", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "COSMIC GATE", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "CRISTOPH", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "CULTURE SHOCK", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "CUTDWN", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "CYCLOPS", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "DA TWEEKAZ", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "DABIN", primary_genre: "Melodic Dubstep", secondary_genre: "Pop EDM" },
  { name: "DARREN PORTER", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "DARUDE", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "DEAD X", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "DEATHPACT", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "DELTA HEAVY", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "DISCIP", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "DJ GIGOLA", primary_genre: "Techno", secondary_genre: "House" },
  { name: "DJ ISAAC", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "DJ MANDY", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "DJ TENNIS B2B CHLOÉ CAILLET", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "DJ TENNIS B2B RED AXES", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "DOCTOR P B2B FLUX PAVILION B2B FUNTCASE", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "DØMINA", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "DREYA V", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "DYEN", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "EAZYBAKED", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "ELI & FUR", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "ELI BROWN", primary_genre: "Techno", secondary_genre: "Tech House" },
  { name: "EPTIC B2B SPACE LACES", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "FALLEN WITH MC DINO", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "FISHER", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "FRANKIE BONES", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "FROST CHILDREN", primary_genre: "Pop EDM", secondary_genre: "Fonk" },
  { name: "FUNK TRIBU", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "GARETH EMERY", primary_genre: "Melodic/Progressive House", secondary_genre: "Pop EDM" },
  { name: "GETTER", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "GHENGAR", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "GORILLAT", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "GRAVAGERZ", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "GRAVEDGR", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "GRIZ B2B WOOLI", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "HAAI B2B LUKE ALESSI", primary_genre: "Techno", secondary_genre: "House" },
  { name: "HAMDI", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "HANNAH LAING", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "HARDWELL", primary_genre: "Pop EDM", secondary_genre: "Techno" },
  { name: "HAYLA", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "HEIDI LAWDEN B2B MASHA MAR", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "HEYZ", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "HNTR", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "HOL!", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "HOLY PRIEST", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "HYBRID MINDS", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "I HATE MODELS", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "ILAN BLUESTONE", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "INDIRA PAGANOTTO", primary_genre: "Psytrance", secondary_genre: "Hard Techno" },
  { name: "INFEKT B2B SAMPLIFIRE", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "INNELLEA", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "INTERPLANETARY CRIMINAL", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "ISABELLA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "JACKIE HOLLANDER", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "JOHN SUMMIT", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "JOSEPH CAPRIATI", primary_genre: "Techno", secondary_genre: "Tech House" },
  { name: "JOSH BAKER", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "KAI WACHI", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "KASKADE", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "KETTAMA", primary_genre: "Techno", secondary_genre: "House" },
  { name: "KEVIN DE VRIES", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "KI/KI", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "KINAHAU", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "KLANGKUENSTLER", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "KLO", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "KOROLOVA", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "KREAM", primary_genre: "House", secondary_genre: "Melodic/Progressive House" },
  { name: "KUKO B2B JOHANNES SCHUSTER", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "LADY FAITH B2B LNY TNZ", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "LAIDBACK LUKE B2B CHUCKIE", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "LAYTON GIORDANI", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "LEVEL UP", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "LEVITY", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "LIL TEXAS", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "LILLY PALMER", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "LINSKA", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "LU.RE", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "LUCIANO", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "LUKE DEAN", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "LUUK VAN DIJK", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "MADDIX", primary_genre: "Techno", secondary_genre: "Pop EDM" },
  { name: "MALUGI", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "MARIA HEALY", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "MARTIN GARRIX", primary_genre: "Pop EDM", secondary_genre: "Melodic/Progressive House" },
  { name: "MARY DROPPINZ", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "MASSANO", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "MASSIMILIANO PAGLIARA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "MATHAME", primary_genre: "Melodic/Progressive House", secondary_genre: "Techno" },
  { name: "MATTY RALPH", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "MAX DEAN", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "MCR-T", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "MEDUZA³", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "MËSTIZA", primary_genre: "Afro House", secondary_genre: "House" },
  { name: "MINK", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "MISH", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "MORGAN SEATREE", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "MPH", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "MURPHY'S LAW", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "MUZZ", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "NICO MORENO", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "NIGHTSTALKER WITH MC DINO", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "NOIZU", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "NOSTALGIX", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "NOTION", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "OBSKÜR", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "OMAR+", primary_genre: "Afro House", secondary_genre: "House" },
  { name: "OMNOM", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "THE OUTLAW", primary_genre: "Fonk", secondary_genre: "Trap" },
  { name: "PARAMIDA", primary_genre: "House", secondary_genre: "Techno" },
  { name: "PAUL OAKENFOLD", primary_genre: "Melodic/Progressive House", secondary_genre: "Pop EDM" },
  { name: "PAUL VAN DYK", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "PEEKABOO", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "PEGASSI", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "PEGGY GOU", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "PLAYER DAVE", primary_genre: "Dubstep", secondary_genre: "Trap" },
  { name: "PORTER ROBINSON (DJ SET)", primary_genre: "Pop EDM", secondary_genre: "Melodic/Progressive House" },
  { name: "THE PRODIGY", primary_genre: "Techno", secondary_genre: "Fonk" },
  { name: "PROSPA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "THE PURGE", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "RAY VOLPE", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "REBEKAH", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "REBŪKE", primary_genre: "Techno", secondary_genre: "Melodic/Progressive House" },
  { name: "RESTRICTED", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "RIOT", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "ROB GEE B2B LENNY DEE", primary_genre: "Hardstyle", secondary_genre: "Hard Techno" },
  { name: "RODDY LIMA", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "ROOLER", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "RØZ", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "THE SAINTS", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "SALUTE B2B CHLOÉ CAILLET", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "SAMA' ABDULHADI", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "SAMMY VIRJI", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "SAN HOLO (WHOLESOME RIDDIM SET)", primary_genre: "Riddim", secondary_genre: "Dubstep" },
  { name: "SAN PACHO", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "SARAH DE WARREN", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "SERAFINA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "SEVEN LIONS", primary_genre: "Melodic Dubstep", secondary_genre: "Pop EDM" },
  { name: "SHINGO NAKAMURA", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "SHIP WREK", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "SIDNEY CHARLES B2B BUSHBABY", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "SIHK", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "SILVA BUMPA", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "SILVIE LOTO", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "SIPPY", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "SKREAM", primary_genre: "Dubstep", secondary_genre: "House" },
  { name: "SLAMM", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "SLUGG", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "SNOW STRIPPERS", primary_genre: "Fonk", secondary_genre: "Pop EDM" },
  { name: "SOFI TUKKER", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "SOLOMUN", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "SPRAY", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "STACY CHRISTINE", primary_genre: "House", secondary_genre: "Tech House" },
  { name: "STAN CHRIST", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "STEVE AOKI", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "SUB FOCUS", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "SUB ZERO PROJECT", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "SUBTRONICS", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "SUPERSTRINGS", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "T78", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "THOMAS SCHUMACHER", primary_genre: "Techno", secondary_genre: "Hard Techno" },
  { name: "TIËSTO", primary_genre: "Pop EDM", secondary_genre: "House" },
  { name: "TIGA", primary_genre: "Techno", secondary_genre: "House" },
  { name: "TINLICKER", primary_genre: "Melodic/Progressive House", secondary_genre: "House" },
  { name: "TOMAN", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "TRACE", primary_genre: "Drums & Bass", secondary_genre: "Drums & Bass" },
  { name: "UNDERWORLD", primary_genre: "Techno", secondary_genre: "House" },
  { name: "VIEZE ASBAK", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "VINTAGE CULTURE", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "VIPERACTIVE", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "VIRTUAL RIOT", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "VTSS (IN THE ROUND)", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "WALKER & ROYCE B2B VNSSA", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "WARFACE", primary_genre: "Hardstyle", secondary_genre: "Hardstyle" },
  { name: "WARUNG", primary_genre: "Techno", secondary_genre: "House" },
  { name: "WAX MOTIF", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "WESTEND", primary_genre: "Tech House", secondary_genre: "House" },
  { name: "WHETHAN", primary_genre: "Pop EDM", secondary_genre: "Trap" },
  { name: "WILLIAM BLACK", primary_genre: "Melodic Dubstep", secondary_genre: "Pop EDM" },
  { name: "WOOLI", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "YDG", primary_genre: "Dubstep", secondary_genre: "Riddim" },
  { name: "YOSUF", primary_genre: "Hard Techno", secondary_genre: "Techno" },
  { name: "ZEDD", primary_genre: "Pop EDM", secondary_genre: "House" }
];